{
 "title": "Nginx metrics",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "req/s by status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(status) (rate(nginx_request_total[$__rate_interval]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "200 req times",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(nginx_request_time_bucket{status=\"200\"}[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "% 200 req times < s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (rate(nginx_request_time_bucket{status=\"200\",le!=\"+Inf\"}[$__rate_interval])) by (le) / ignoring(le) group_left sum (rate(nginx_request_time_count{status=\"200\"}[$__rate_interval]))",
     "legendFormat": "{{ le }}s"
    }
   ]
  }
 ]
}