{
 "title": "Queues overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "GCPProject",
    "label": "Project",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Raw events Pub/Sub Subscription",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Unacked events",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "raw-events-subscription"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/num_undelivered_messages",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$GCPProject",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Preprocess events worker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(preprocessed_events_total[$__interval])",
     "legendFormat": "{{ routing_key }}"
    }
   ]
  },
  {
   "title": "Events Pub/Sub Subscription",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Unacked events",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "events-subscription"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/num_undelivered_messages",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$GCPProject",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Enrich events worker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(enriched_events_total[$__interval])",
     "legendFormat": "{{ event_type }}"
    }
   ]
  },
  {
   "title": "Splunk Pub/Sub Subscription",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Unacked events",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "splunk-store-enriched-events-subscription"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/num_undelivered_messages",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$GCPProject",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Splunk worker",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(stored_events_total{job=\"store worker splunk\"}[$__interval])",
     "legendFormat": "{{ event_type }}"
    }
   ]
  },
  {
   "title": "ES Pub/Sub Subscription",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "Unacked events",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "elasticsearch-store-enriched-events-subscription"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "pubsub.googleapis.com/subscription/num_undelivered_messages",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$GCPProject",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "ES worker",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(stored_events_total{job=\"store worker elasticsearch\"}[$__interval])",
     "legendFormat": "{{ event_type }}"
    }
   ]
  }
 ]
}