{
 "title": "Splunk storage troubleshooting",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Unacked messsages in Pubsub queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.subscription_id",
       "=",
       "splunk-store-enriched-events-subscription",
       "AND",
       "metric.type",
       "=",
       "pubsub.googleapis.com/subscription/num_undelivered_messages"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$project"
     }
    }
   ]
  },
  {
   "title": "Stored events per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(stored_events_total{job=\"store worker splunk\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Journald logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketId": "global/buckets/_Default",
     "projectName": "$project",
     "queryText": "jsonPayload.systemd_unit=\"zentral_store_worker_splunk.service\"",
     "viewId": "_AllLogs"
    }
   ]
  }
 ]
}