{
 "title": "major OS Versions",
 "time": { "from": "now-3d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "last_n_days",
    "label": "Last N Days",
    "query": {
     "query": "label_values(zentral_inventory_os_versions_bucket, le)"
    }
   },
   {
    "name": "name",
    "label": "OS Name",
    "query": {
     "query": "label_values(zentral_inventory_os_versions_bucket, name)"
    }
   },
   {
    "name": "source_name",
    "label": "Source",
    "query": {
     "query": "label_values(zentral_inventory_os_versions_bucket, source_name)"
    }
   },
   { "name": "min_percent", "label": "Min %", "query": "0,0.1,1,10" }
  ]
 },
 "panels": [
  {
   "title": "major OS versions %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum without(minor, patch, build) (zentral_inventory_os_versions_bucket{name=\"$name\", le=\"$last_n_days\", source_name=\"$source_name\"})) * 100 / ignoring(major) group_left sum without(major, minor, patch, build) (zentral_inventory_os_versions_bucket{name=\"$name\", le=\"$last_n_days\", source_name=\"$source_name\"}) > $min_percent",
     "legendFormat": "{{major}}"
    }
   ]
  },
  {
   "title": "major OS versions absolute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "(sum without(minor, patch, build) (zentral_inventory_os_versions_bucket{name=\"$name\", le=\"$last_n_days\", source_name=\"$source_name\"})) > 0",
     "legendFormat": "{{major}}"
    },
    {
     "expr": "sum(zentral_inventory_active_machines_bucket{source_name=\"$source_name\",le=\"$last_n_days\"})",
     "legendFormat": "fleet"
    }
   ]
  },
  {
   "title": "major OS versions % fleet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "(sum without(minor, patch, build) (zentral_inventory_os_versions_bucket{le=\"$last_n_days\", source_name=\"$source_name\", name=\"$name\"})) * 100 / ignoring(name, major, minor, patch, build, platform) group_left sum without(machine_type, platform) (zentral_inventory_active_machines_bucket{source_name=\"$source_name\", le=\"$last_n_days\"}) > 0",
     "legendFormat": "{{major}}"
    }
   ]
  }
 ]
}