{
 "title": "macOS app",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "last_n_days",
    "label": "Last N Days",
    "query": {
     "query": "label_values(zentral_inventory_osx_apps_bucket, le)"
    }
   },
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values(zentral_inventory_osx_apps_bucket, name)"
    }
   },
   {
    "name": "source_name",
    "label": "Source",
    "query": {
     "query": "label_values(zentral_inventory_osx_apps_bucket, source_name)"
    }
   },
   { "name": "min_percent", "label": "Min %", "query": "0,0.1,1,10" }
  ]
 },
 "panels": [
  {
   "title": "macOS app %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "zentral_inventory_osx_apps_bucket{name=\"$name\", le=\"$last_n_days\", source_name=\"$source_name\"} * 100 / ignoring(version) group_left sum without(version) (zentral_inventory_osx_apps_bucket{name=\"$name\", le=\"$last_n_days\", source_name=\"$source_name\"}) > $min_percent",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "macOS app absolute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "zentral_inventory_osx_apps_bucket{name=\"$name\", le=\"$last_n_days\", source_name=\"$source_name\"} > 0",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "sum(zentral_inventory_active_machines_bucket{source_name=\"$source_name\",le=\"$last_n_days\"})",
     "legendFormat": "fleet"
    }
   ]
  },
  {
   "title": "macOS app % fleet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "zentral_inventory_osx_apps_bucket{le=\"$last_n_days\", source_name=\"$source_name\", name=\"$name\"} * 100 / ignoring(name, version) group_left sum without(machine_type, platform) (zentral_inventory_active_machines_bucket{source_name=\"$source_name\", le=\"$last_n_days\"}) > 0",
     "legendFormat": "{{version}}"
    },
    { "legendFormat": "fleet" }
   ]
  }
 ]
}