{
 "title": "MDM Installed Artifact",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "last_n_days",
    "label": "Last N Days",
    "query": {
     "query": "label_values(zentral_mdm_target_artifacts_bucket,le)"
    }
   },
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values(zentral_mdm_target_artifacts_bucket,name)"
    }
   },
   { "name": "min_install_count", "label": "Min Install Count", "query": "1,5,10,20,50,100" }
  ]
 },
 "panels": [
  {
   "title": "$name - % total",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (version) (zentral_mdm_target_artifacts_bucket{name=\"$name\", le=\"$last_n_days\", present=\"true\"}) >= $min_install_count) * 100 / ignoring(version) group_left sum without(version) (sum by (version) (zentral_mdm_target_artifacts_bucket{name=\"$name\", le=\"$last_n_days\", present=\"true\"}) >= $min_install_count)",
     "legendFormat": "{{ status }} {{ version }}"
    }
   ]
  },
  {
   "title": "$name - Absolute",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (version) (zentral_mdm_target_artifacts_bucket{name=\"$name\",le=\"$last_n_days\", present=\"true\"}) >= $min_install_count",
     "legendFormat": "{{ version }}"
    },
    {
     "expr": "sum(zentral_mdm_devices{le=\"$last_n_days\",blueprint!=\"_\"})",
     "legendFormat": "fleet"
    }
   ]
  },
  {
   "title": "$name - % fleet",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (version) (zentral_mdm_target_artifacts_bucket{name=\"$name\",le=\"$last_n_days\",present=\"true\"}) >= $min_install_count) * 100 / ignoring (version) group_left sum(sum(zentral_mdm_devices{le=\"$last_n_days\",blueprint!=\"_\"}))",
     "legendFormat": "{{ version }}"
    }
   ]
  }
 ]
}