{
 "title": "Munki package",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "last_n_days",
    "label": "Last N Days",
    "query": {
     "query": "label_values(zentral_munki_installed_pkginfos_bucket, le)"
    }
   },
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values(zentral_munki_installed_pkginfos_bucket, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$name - % total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "zentral_munki_installed_pkginfos_bucket{name=\"$name\", le=\"$last_n_days\"} * 100 / ignoring(version) group_left sum without(version) (zentral_munki_installed_pkginfos_bucket{name=\"$name\", le=\"$last_n_days\"}) > 0",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "$name - Absolute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "zentral_munki_installed_pkginfos_bucket{name=\"$name\",le=\"$last_n_days\"} > 0",
     "legendFormat": "{{ version }}"
    },
    {
     "expr": "zentral_munki_active_machines_bucket{le=\"$last_n_days\"}",
     "legendFormat": "fleet"
    }
   ]
  },
  {
   "title": "$name - % fleet",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "zentral_munki_installed_pkginfos_bucket{name=\"$name\",le=\"$last_n_days\"} * 100 / ignoring (name, version) group_left zentral_munki_active_machines_bucket{le=\"$last_n_days\"} > 0",
     "legendFormat": "{{ version }}"
    }
   ]
  }
 ]
}