{
 "title": "Osquery overview",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Unique machines by user agent",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "request.user_agent",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "machine_serial_number", "id": "1", "type": "cardinality" }
     ],
     "query": "type:osquery_request",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Osquery enrollments",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "osquery_enrollment.action",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:osquery_enrollment",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Osquery machines with up-to-date inventory (1d)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (platform) (zentral_inventory_active_machines_bucket{source_name=\"osquery\",le=\"1\"})",
     "legendFormat": "{{ platform }}"
    },
    {
     "expr": "sum (zentral_inventory_active_machines_bucket{source_name=\"osquery\",le=\"1\"})",
     "legendFormat": "ALL"
    }
   ]
  },
  {
   "title": "Osquery req/$__interval by user agent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "request.user_agent",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:osquery_request",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Osquery enrollment/h by action",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "osquery_enrollment.action",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "created_at", "id": "2", "settings": { "interval": "1h" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:osquery_enrollment",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Machines with multiple enrollments",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "machine_serial_number",
       "id": "3",
       "settings": { "min_doc_count": "2", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "machine.platform",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "osquery_enrollment.action",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "request.user_agent",
       "id": "6",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "machine.osquery.name",
       "id": "7",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:osquery_enrollment",
     "timeField": "created_at"
    }
   ]
  }
 ]
}