{
 "title": "Osquery overview",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Osquery requests  by user agent / $__interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n $__timeInterval(created_at) AS time,\n metadata.request.user_agent.:String AS user_agent,\n count(*) as \" \"\nFROM zentral_events\nWHERE\n $__timeFilter(created_at)\n AND ( created_at  >= $__fromTime AND created_at <= $__toTime )\n AND type = 'osquery_request'\nGROUP BY user_agent, time\nORDER BY time ASC\nLIMIT 100000"
    }
   ]
  },
  {
   "title": "Unique machines by user agent / $__interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n $__timeInterval(created_at) AS time,\n metadata.request.user_agent.:String AS user_agent,\n count(distinct metadata.machine_serial_number.:String) as \" \"\nFROM zentral_events\nWHERE\n $__timeFilter(created_at)\n AND ( created_at  >= $__fromTime AND created_at <= $__toTime )\n AND type = 'osquery_request'\nGROUP BY user_agent, time\nORDER BY time ASC\nLIMIT 100000"
    }
   ]
  },
  {
   "title": "Osquery enrollments / $__interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n $__timeInterval(created_at) AS time,\n payload.action.:String as action,\n count(*) as \" \"\nFROM zentral_events\nWHERE\n $__timeFilter(created_at)\n AND ( created_at  >= $__fromTime AND created_at <= $__toTime )\n AND type = 'osquery_enrollment'\nGROUP BY action, time\nORDER BY time ASC\nLIMIT 100000"
    }
   ]
  },
  {
   "title": "Osquery machines with up-to-date inventory (1d)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (platform) (zentral_inventory_active_machines_bucket{source_name=\"osquery\",le=\"1\"})",
     "legendFormat": "{{ platform }}"
    },
    {
     "expr": "sum (zentral_inventory_active_machines_bucket{source_name=\"osquery\",le=\"1\"})",
     "legendFormat": "ALL"
    }
   ]
  },
  {
   "title": "Machines with multiple enrollments",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\n metadata.machine_serial_number.:String AS \"serial number\",\n count(*) as enrollments\nFROM zentral_events\nWHERE\n created_at  >= $__fromTime AND created_at <= $__toTime\n AND type = 'osquery_enrollment'\nGROUP BY \"serial number\"\nHAVING enrollments > 1\nORDER BY enrollments DESC, \"serial number\" ASC"
    }
   ]
  }
 ]
}