{
 "title": "Santa overview (Elasticsearch)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Santa events / $__interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tags:santa",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Top 20 Allow Unknown files",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "santa_event.file_name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      {
       "field": "santa_event.file_sha256",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:santa_event AND santa_event.decision:ALLOW_UNKNOWN",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Top 20 Allow Unknown Team IDs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "santa_event.team_id",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      {
       "field": "santa_event.signing_cert_0.org",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:santa_event AND santa_event.decision:ALLOW_UNKNOWN",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Top 20 Allow Unknown Signing IDs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "santa_event.signing_id",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      {
       "field": "santa_event.signing_cert_0.org",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:santa_event AND santa_event.decision:ALLOW_UNKNOWN",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Top 20 Allow Unknown certificates",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "santa_event.signing_cert_0.sha256",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      {
       "field": "santa_event.signing_cert_0.org",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      },
      {
       "field": "santa_event.signing_cert_0.valid_until",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:santa_event AND santa_event.decision:ALLOW_UNKNOWN",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Santa user agents",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 43 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "request.user_agent",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "machine_serial_number", "id": "1", "type": "cardinality" }
     ],
     "query": "type:santa_event",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Santa rules",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 43 },
   "targets": [
    {
     "expr": "zentral_santa_rules",
     "legendFormat": "{{ ruleset }} {{ target_type }} {{ policy }}"
    }
   ]
  }
 ]
}