{
 "title": "Santa overview",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Santa events / $__interval",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n $__timeInterval(created_at) AS time,\n payload.decision.:String AS decision,\n count(*) as events\nFROM zentral_events\nWHERE\n $__timeFilter(created_at)\n AND ( created_at  >= $__fromTime AND created_at <= $__toTime )\n AND type = 'santa_event'\nGROUP BY decision, time\nORDER BY time ASC\nLIMIT 100000"
    }
   ]
  },
  {
   "title": "Santa rules",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "zentral_santa_rules_total",
     "legendFormat": "{{ ruleset }} {{ target_type }} {{ policy }}"
    }
   ]
  },
  {
   "title": "Top 100 Allow Unknown files",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\npayload.file_path.:String file_path,\npayload.file_name.:String file_name,\npayload.cdhash.:String cdhash,\npayload.file_sha256.:String sha_256,\ncount(*)\nFROM zentral_events\nWHERE type = 'santa_event'\nAND payload.decision.:String = 'ALLOW_UNKNOWN'\nAND ( created_at  >= $__fromTime AND created_at <= $__toTime )\nGROUP BY file_path, file_name, cdhash, sha_256\nORDER BY count(*) DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Top 100 Allow Unknown Team IDs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\npayload.team_id.:String team_id,\npayload.signing_cert_0.org.:String org,\ncount(*)\nFROM zentral_events\nWHERE type = 'santa_event'\nAND team_id IS NOT NULL\nAND payload.decision.:String = 'ALLOW_UNKNOWN'\nAND ( created_at  >= $__fromTime AND created_at <= $__toTime )\nGROUP BY team_id, org\nORDER BY count(*) DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Top 100 Allow Unknown Signing IDs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\npayload.signing_id.:String signing_id,\npayload.signing_cert_0.org.:String org,\ncount(*)\nFROM zentral_events\nWHERE type = 'santa_event'\nAND signing_id IS NOT NULL\nAND payload.decision.:String = 'ALLOW_UNKNOWN'\nAND ( created_at  >= $__fromTime AND created_at <= $__toTime )\nGROUP BY signing_id, org\nORDER BY count(*) DESC\nLIMIT 100;"
    }
   ]
  }
 ]
}