{
 "title": "Santa overview",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Santa events / $__interval",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "type",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "created_at", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "tags:santa",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Santa user agents",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "request.user_agent",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "machine_serial_number", "id": "1", "type": "cardinality" }
     ],
     "query": "type:santa_event",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Top 10 Allow Unknowns",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "santa_event.file_name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "type:santa_event AND santa_event.decision:ALLOW_UNKNOWN",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Santa rules",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "zentral_santa_rules",
     "legendFormat": "{{ ruleset }} {{ target_type }} {{ policy }}"
    }
   ]
  }
 ]
}